### ISSUE TITLE
Getting Error:- "Caused by: java.util.zip.ZipException: zip END header not found"

### ISSUE THREAD

**Issue by Lets-A-Code** [Hexeption/MCP-Reborn#110]
I Am Gating This Error:-
"
Exception in thread "main" java.lang.RuntimeException: Failed to read library!
	at org.cadixdev.vignette.VignetteMain.main(VignetteMain.java:137)
Caused by: java.util.zip.ZipException: zip END header not found
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1306)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1520)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:172)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:106)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:338)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:287)
	at org.cadixdev.atlas.util.NIOHelper.openZip(NIOHelper.java:38)
	at org.cadixdev.atlas.jar.JarFile.<init>(JarFile.java:51)
	at org.cadixdev.atlas.Atlas.use(Atlas.java:93)
	at org.cadixdev.vignette.VignetteMain.main(VignetteMain.java:135)
Caused by: java.util.zip.ZipException: zip END header not found

  Task :mcp:setupMCP FAILED

Execution failed for task ':mcp:setupMCP'.
  Process 'command 'C:\Program Files\AdoptOpenJDK\jdk-16.0.1.9-hotspot\bin\java.exe'' finished with non-zero exit value 1
"

**Comment by Lets-A-Code** [comment]
I FIXED IT!
you have to delete the .gradle folder in C:\Users\USER_NAME\ and try running it again.
It will make the fixed .gradle folder and the errors will be gone.
