### ISSUE TITLE
Where is the assets/textures located?

### ISSUE THREAD

**Issue by redfoxuwu** [Hexeption/MCP-Reborn#179]
before i could throw it in the actual project, than later it worked by throwing it in the run folder, now I had to add assets to client-extra.jar and it worked, now anything I try to do it will not find the assets folder, nothing wrong with my code, optifine can't even find the goddamn assets/textures file

[12:55:09] [VersionCheck/INFO]: [OptiFine] java.io.FileNotFoundException: http://optifine.net/version/1.18.1/HD_U.txt

[12:55:12] [Render thread/INFO]: [STDERR]: java.io.IOException: Problem reading font data.

[12:55:12] [Render thread/INFO]: [STDERR]: java.io.IOException: Problem reading font data.
[12:55:12] [Render thread/INFO]: [STDERR]: 	at java.desktop/java.awt.Font.createFont0(Font.java:1208)
[12:55:12] [Render thread/INFO]: [STDERR]: 	at java.desktop/java.awt.Font.createFont(Font.java:1076)

**Comment by frisby-ninja** [comment]
I believe MCP downloads the assets from an external source, so I'm pretty sure Optifine does the same. It may be a problem with the importing.
