### ISSUE TITLE
1.18.1 Client does not launch: Could not initialize class com.mojang.blaze3d.systems.RenderSystem

### ISSUE THREAD

**Issue by AdrianR3** [Hexeption/MCP-Reborn#182]
I've been trying to run the client with the runClient task, but it crashes with the following error:

> Exception in thread "Render thread" [16:38:13] [Render thread/INFO]: [STDERR]: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
[16:38:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.SystemReport.setDetail(SystemReport.java:62)
[16:38:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.fillSystemReport(Minecraft.java:2264)
[16:38:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.fillReport(Minecraft.java:2257)
[16:38:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:178)

**System Info:**

M1 Mac
MacOS Monterey 12.2.1

**Comment by fmbearmf** [comment]
Use Rosetta 2 (download an x86-64 build of java)
