### ISSUE TITLE
runclient task stopped working for no reason

### ISSUE THREAD

**Issue by bastien-snk** [Hexeption/MCP-Reborn#198]
Hello, I got this error overnight, without changing anything. I don't touch the registry except for Blocks & Items.
I've been stuck for 2 days and I've looked at it and nobody talks about it on the net.

Setup:
- OS: Mac
- JDK: 17

```Exception in thread "main" java.lang.IllegalStateException: Some intrusive holders were not added to registry: [Reference{null=air}, Reference{null=air}]
        at net.minecraft.core.MappedRegistry.freeze(MappedRegistry.java:297)
        at net.minecraft.core.Registry.freezeBuiltins(Registry.java:429)
        at net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:57)
        at net.minecraft.client.main.Main.main(Main.java:138)

FAILURE: Build failed with an exception.
```

**Comment by TheKodeToad** [comment]
Ah, well clearly there was a problem freezing the mapped registry.
I think we're gonna need the full log. And the code around where the error actually happens.
Show something like this
```
java.lang.OhNoException: Something bad just happened
    at UnsafeEnumManipulation.insertMember(UnsafeEnumManipulation.java:34)
    at VeryUnsafeMagic.doStuff(VeryUnsafeMagic.java:64)

```
In this case, you would also share line 34 of UnsafeEnumManipulation.java.
I'm not trying to patronise you or anything, I'm just trying to be clear and helpful.
