### ISSUE TITLE
1.19 instantly crashes

### ISSUE THREAD

**Issue by Manthan-Thakkar-20** [Hexeption/MCP-Reborn#215]
When I use runclient:
![image](https://user-images.githubusercontent.com/109627013/184332373-43bcfee6-e0ca-49be-964a-894e706628d5.png)

this is the terminal output:
![image](https://user-images.githubusercontent.com/109627013/184332446-0cfcbc31-7f23-4cca-893d-c76a379560ab.png)

This happened after I switched my JAVA_HOME variable from pointing to Java 8 to Java 17, since before it was giving this error:

```
> Task :runclient FAILED
Error: A JNI error has occurred, please check your installation and try again
A JNI error has occurred, please check your installation and try again

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)

Execution failed for task ':runclient'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_333\bin\java.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

**Comment by Manthan-Thakkar-20** [comment]
### THIS IS THE FIX:

This error occurs as IntelliJ thinks that Oracle's Java 17 is a **JRE** and not a **JDK**.

To fix this, go to File > Settings> Build, Execution, Deployment > Build Tools > Gradle. Then click Gradle JVM > Download JDK and select the number 18 in the version dropdown. The vendor should show as Amazon Corretto (although others may or may not work). Click Download > Apply > OK and then run the client. It will download the JDK and then start up correctly.
