### ISSUE TITLE
Can't run setup

### ISSUE THREAD

**Issue by RedCDev** [Hexeption/MCP-Reborn#74]
I've tried to run the setup on both IntelliJ and Eclipse, but it always throws the same error.

> Task :mcp:downloadConfig UP-TO-DATE

> Task :mcp:setupMCP
Setting up MCP environment
Initializing steps
Executing steps
 > Running 'downloadManifest'
 > Running 'downloadJson'
 > Running 'downloadClient'
 > Running 'downloadServer'
 > Running 'stripClient'
 > Running 'stripServer'
 > Running 'merge'
 > Running 'rename'
 > Running 'mcinject'
 > Running 'listLibraries'
 > Running 'decompile'
Exception in thread "main" java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file
	at org.jetbrains.java.decompiler.struct.StructContext.addSpace(StructContext.java:102)
	at org.jetbrains.java.decompiler.struct.StructContext.addSpace(StructContext.java:70)
	at org.jetbrains.java.decompiler.main.Fernflower.addLibrary(Fernflower.java:109)
	at org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler.addLibrary(ConsoleDecompiler.java:177)
	at org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler.main(ConsoleDecompiler.java:117)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
	at org.jetbrains.java.decompiler.struct.StructContext.addArchive(StructContext.java:135)
	at org.jetbrains.java.decompiler.struct.StructContext.addSpace(StructContext.java:92)
	... 4 more

> Task :mcp:setupMCP FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mcp:setupMCP'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_231\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
2 actionable tasks: 1 executed, 1 up-to-date

**Comment by GitCat3** [comment]
this has also happened for me, can someone please help?

**Comment by Hezuikn** [comment]
yall need a diff jdk
