### ISSUE TITLE
Built release JAR doesn't start from the launcher

### ISSUE THREAD

**Issue by bo3tools** [Hexeption/MCP-Reborn#85]
Using latest MCP Reborn 1.16.4 (commit https://github.com/Hexeption/MCP-Reborn/commit/b9e7a12e8d55289f49d466234db8e25fdd8b8c03).

The client runs from IDEA successfully (all textures and sounds present, no errors), but the built "libs/mcp-reborn-1.0.0.jar" does not start from the launcher.

Steps to reproduce:

* Clear `%HOMEPATH%\.gradle\caches` (resolves to `C:\Users\%USERNAME%\.gradle\caches`)
* Import project from existing sources > Choose the downloaded MCP-Reborn folder
* Wait for the gradle project to be configured
* Run task "setup" from "mcp"
* Run task "copyAssets" from "mcp"
* Edit configurations > Add new configuration > Application
* Set "Main class" to "mcp.client.Start"
* Set "Working directory" to "run" folder from root
* Set "Use classpath of module" to "mcp-reborn.main"
* Run created configuration, confirm the project starts from IDEA
* Run task "build" from "build"
* Copy the release jar "mcp-reborn-1.0.0.jar" from "build/libs"
* Create and setup a new launcher version to use with build client jar
* Launch the version from launcher
* The game crashes

```
Exception in thread "main" java.lang.NoSuchMethodError: com.mojang.serialization.MapCodec.setPartial(Ljava/util/function/Supplier;)Lcom/mojang/serialization/MapCodec;
    at net.minecraft.state.StateContainer.func_241487_a_(StateContainer.java:74)
    at net.minecraft.state.StateContainer.<init>(StateContainer.java:41)
    at net.minecraft.state.StateContainer$Builder.func_235882_a_(StateContainer.java:149)
    at net.minecraft.block.Block.<init>(Block.java:154)
    at net.minecraft.block.SnowyDirtBlock.<init>(SnowyDirtBlock.java:15)
    at net.minecraft.block.SpreadableSnowyDirtBlock.<init>(SpreadableSnowyDirtBlock.java:13)
    at net.minecraft.block.GrassBlock.<init>(GrassBlock.java:14)
    at net.minecraft.block.Blocks.<clinit>(Blocks.java:37)
    at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12)
    at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(ConfiguredSurfaceBuilders.java:7)
    at net.minecraft.util.registry.WorldGenRegistries.lambda$static$0(WorldGenRegistries.java:33)
    at net.minecraft.util.registry.WorldGenRegistries$$Lambda$107/752684363.get(Unknown Source)
    at net.minecraft.util.registry.WorldGenRegistries.lambda$static$6(WorldGenRegistries.java:85)
    at net.minecraft.util.registry.WorldGenRegistries$$Lambda$115/2011997442.accept(Unknown Source)
    at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
    at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:84)
    at net.minecraft.util.registry.Registry.<clinit>(Registry.java:444)
    at net.minecraft.util.registry.Bootstrap.register(Bootstrap.java:38)
    at net.minecraft.client.main.Main.main(Main.java:123)
```

**Comment by Hexeption** [comment]
You need to put the assets into the jar
